"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/AuthProvider";
import { LlmStreamOutput } from "@/components/LlmStreamOutput";
import { getAssessment, getBorrowerUpdate } from "@/lib/api";

export default function BorrowerSelfPage() {
  const { session, setSession, ready } = useAuth();
  const router = useRouter();
  const [updateText, setUpdateText] = useState<string | null>(null);
  const [needsAttention, setNeedsAttention] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const borrowerId = session?.user.borrower_id ?? "";

  useEffect(() => {
    if (!ready || !borrowerId) return;
    if (!session) {
      router.replace("/");
      return;
    }
    if (session.user.role !== "borrower") {
      router.replace("/dashboard");
      return;
    }

    setUpdateText(null);
    setError(null);
    setLoading(true);

    Promise.all([
      getAssessment(session.token, borrowerId),
      getBorrowerUpdate(session.token, borrowerId),
    ])
      .then(([assessment, update]) => {
        setNeedsAttention(assessment.risk_category !== "Low");
        setUpdateText(update.explanation);
      })
      .catch((e: Error) => setError(e.message))
      .finally(() => setLoading(false));
  }, [ready, session, router, borrowerId]);

  if (!ready) return null;
  if (!session || session.user.role !== "borrower" || !borrowerId) return null;

  return (
    <main className="shell fade-in">
      <header className="topbar">
        <div className="brand">
          <div className="brand-mark">Biz2X Early Warning</div>
          <div className="brand-sub">
            Your account update · {session.user.name}
          </div>
        </div>
        <button
          type="button"
          className="btn btn-ghost"
          onClick={() => {
            setSession(null);
            router.push("/");
          }}
        >
          Sign out
        </button>
      </header>

      {error && (
        <p className="panel" style={{ color: "var(--critical)" }}>
          {error}
        </p>
      )}

      <div className="stack">
        {loading && <p className="panel muted">Loading your account summary…</p>}

        {!loading && (
          <section className="panel">
            <p style={{ margin: 0, lineHeight: 1.55 }}>
              {needsAttention
                ? "We've reviewed your recent repayment activity and have a short update for you below."
                : "Your recent repayments look good. Here's a quick summary of your account."}
            </p>
          </section>
        )}

        {updateText && (
          <section className="panel" data-testid="borrower-self-view">
            <h2 style={{ marginTop: 0, fontSize: "1.15rem" }}>Your account update</h2>
            <LlmStreamOutput text={updateText} emptyLabel="No update available." />
            <p className="muted" style={{ fontSize: "0.8rem", marginTop: "0.65rem", marginBottom: 0 }}>
              Deterministic summary · not generated by AI
            </p>
          </section>
        )}
      </div>
    </main>
  );
}
